### ISSUE TITLE
Use file once we update ansible from 2.0.0.2

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#457]
Remove `mkdir` and use `file`

in `install-sync-gateway-source.yml`

```
  tasks:
  # Copy sync_gateway binary from centos user
  - name: Creates /opt/couchbase-sync-gateway
    shell: mkdir /opt/couchbase-sync-gateway
  - name: Creates /opt/couchbase-sync-gateway/bin
    shell: mkdir /opt/couchbase-sync-gateway/bin
  - name: copy sync_gateway binary to /opt/
    shell: cp /home/centos/godeps/bin/sync_gateway /opt/couchbase-sync-gateway/bin/

- hosts: sg_accels
  any_errors_fatal: true

  tasks:
  # Copy sg_accel binary from centos user
  - name: Creates /opt/couchbase-sg-accel
    shell: mkdir /opt/couchbase-sg-accel
  - name: Creates /opt/couchbase-sg-accel/bin
    shell: mkdir /opt/couchbase-sg-accel/bin
  - name: copy sg_accel binary to /opt/
    shell: cp /home/centos/godeps/bin/sg_accel /opt/couchbase-sg-accel/bin/
```
